mentor-us/backend

- src/src/main/java/com/hcmus/mentor/backend/web/infrastructure/security/SecurityConfig.java
Task: https://somesandwich2.atlassian.net/browse/MU-39
> Update cors rule MU-39

- INSTALL.md
Task: https://somesandwich2.atlassian.net/browse/MU-26
> Add missing command when init MongoDB MU-26

- docs/Development.md
- src/src/main/java/com/hcmus/mentor/backend/usecase/users/authenticateuser/TokenModelGenerator.java
- src/src/main/java/com/hcmus/mentor/backend/usecase/users/authenticateuser/loginuser/LoginUserCommandHandler.java
- src/src/main/java/com/hcmus/mentor/backend/usecase/users/authenticateuser/refreshtoken/RefreshTokenCommandHandler.java
- src/src/main/java/com/hcmus/mentor/backend/web/infrastructure/security/oauth2/OAuth2AuthenticationSuccessHandler.java
Task: https://somesandwich2.atlassian.net/browse/MU-39
> Add subject to JWT token and update document about development MU-39

- .github/workflows/build-and-deploy-dev.yml
Task: https://somesandwich2.atlassian.net/browse/MU-119
> Update development ci/cd pipeline MU-119

- src/src/main/java/com/hcmus/mentor/backend/infrastructure/fileupload/BlobStorage.java
- src/src/main/java/com/hcmus/mentor/backend/infrastructure/fileupload/impl/S3FileStorage.java
- src/src/main/java/com/hcmus/mentor/backend/web/controller/FileController.java
https://somesandwich2.atlassian.net/browse/MU-182
> Implement get presignURL MU-182

- src/src/main/java/com/hcmus/mentor/backend/controller/MessageController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/payload/request/MentionUserCommand.java
https://somesandwich2.atlassian.net/browse/MU-201
> Change request param to body in mention MU-201

- src/src/main/java/com/hcmus/mentor/backend/controller/FileController.java
- src/src/main/java/com/hcmus/mentor/backend/service/fileupload/BlobStorage.java
- src/src/main/java/com/hcmus/mentor/backend/service/fileupload/impl/S3FileStorage.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/GroupServiceImpl.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/MessageServiceImpl.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/UserServiceImpl.java
https://somesandwich2.atlassian.net/browse/MU-182
> Update MinIO file and add javadoc MU-182

- src/src/main/java/com/hcmus/mentor/backend/controller/UserController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/payload/request/AddAdditionEmailRequest.java
- src/src/main/java/com/hcmus/mentor/backend/controller/payload/request/RemoveAdditionalEmailRequest.java
- src/src/main/java/com/hcmus/mentor/backend/controller/payload/returnCode/UserReturnCode.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/user/addaddtionalemail/AddAdditionalEmailCommand.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/user/addaddtionalemail/AddAdditionalEmailCommandHandler.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/user/addaddtionalemail/AddAdditionalEmailResult.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/user/removeadditionalemail/RemoveAdditionalEmailCommand.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/user/removeadditionalemail/RemoveAdditionalEmailHandler.java
- src/src/main/java/com/hcmus/mentor/backend/domain/User.java
- src/src/main/java/com/hcmus/mentor/backend/repository/UserRepository.java
- src/src/main/java/com/hcmus/mentor/backend/security/CustomUserDetailService.java
- src/src/main/java/com/hcmus/mentor/backend/service/UserService.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/UserServiceImpl.java
- src/src/main/java/com/hcmus/mentor/backend/util/StringListUtils.java
https://somesandwich2.atlassian.net/browse/MU-184
> Add additional email to User entity and update validate email when login MU-184

- src/src/main/java/com/hcmus/mentor/backend/config/MongoDbConfig.java
- src/src/main/java/com/hcmus/mentor/backend/config/QuartzConfig.java
- src/src/main/java/com/hcmus/mentor/backend/controller/MessageController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/VoteController.java
- src/src/main/java/com/hcmus/mentor/backend/domain/Vote.java
- src/src/main/java/com/hcmus/mentor/backend/repository/MessageRepository.java
- src/src/main/java/com/hcmus/mentor/backend/repository/ReminderRepository.java
- src/src/main/java/com/hcmus/mentor/backend/service/MessageService.java
- src/src/main/java/com/hcmus/mentor/backend/service/ReminderService.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/MessageServiceImpl.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/ReminderServiceImpl.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/VoteServiceImpl.java
https://somesandwich2.atlassian.net/browse/MU-179
> Update votebox to latest order when new vote is cast MU-179

- src/src/main/java/com/hcmus/mentor/backend/controller/MessageController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/payload/response/messages/MessageDetailResponse.java
- src/src/main/java/com/hcmus/mentor/backend/controller/payload/response/messages/MessageResponse.java
- src/src/main/java/com/hcmus/mentor/backend/domain/Message.java
https://somesandwich2.atlassian.net/browse/MU-222
> Add field isEdited and editedAt to Message entity MU-222

- src/src/main/java/com/hcmus/mentor/backend/controller/GroupController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/payload/request/groups/UpdateGroupImageRequest.java
- src/src/main/java/com/hcmus/mentor/backend/service/GroupService.java
- src/src/main/java/com/hcmus/mentor/backend/service/fileupload/impl/S3FileStorage.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/GroupServiceImpl.java
https://somesandwich2.atlassian.net/browse/MU-173
> Api update group image MU-173

- src/src/main/java/com/hcmus/mentor/backend/security/principal/oauth2/CustomOidcUserService.java
https://somesandwich2.atlassian.net/browse/MU-184
> Fix login by additional email in oauth2 MU-184

- src/src/main/java/com/hcmus/mentor/backend/service/MailService.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/GroupServiceImpl.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/MailServiceImpl.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/UserServiceImpl.java
- src/src/main/resources/application-dev.yml.template
- src/src/main/resources/application-local.yml.template
- src/src/main/resources/application-prod.yml.template
- src/src/main/resources/templates/mails/welcom-to-group-mail.html
- src/src/main/resources/templates/mails/welcome-to-app.html
https://somesandwich2.atlassian.net/browse/MU-244
> Change email template for invite new user MU-244

- src/src/main/java/com/hcmus/mentor/backend/service/impl/GroupServiceImpl.java
https://somesandwich2.atlassian.net/browse/MU-196
> Fix image url in group dto MU-196

- src/src/main/java/com/hcmus/mentor/backend/service/impl/ReminderServiceImpl.java
- src/src/main/resources/templates/MEETING_REMINDER.html
- src/src/main/resources/templates/TASK_REMINDER.html
https://somesandwich2.atlassian.net/browse/MU-244
> Add new url of deeplink for meeting and task MU-244

- src/src/main/java/com/hcmus/mentor/backend/controller/GroupController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/exception/ForbiddenException.java
- src/src/main/java/com/hcmus/mentor/backend/controller/payload/response/groups/UpdateGroupAvatarResponse.java
- src/src/main/java/com/hcmus/mentor/backend/security/handler/GlobalControllerExceptionHandler.java
- src/src/main/java/com/hcmus/mentor/backend/service/GroupService.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/GroupServiceImpl.java
https://somesandwich2.atlassian.net/browse/MU-249
> Update API update avatar group MU-249

- src/src/main/java/com/hcmus/mentor/backend/service/impl/GroupServiceImpl.java
https://somesandwich2.atlassian.net/browse/MU-264
> Update the logic not remove the permission for private channel or private message MU-264

- src/src/main/java/com/hcmus/mentor/backend/controller/payload/response/messages/MessageDetailResponse.java
- src/src/main/java/com/hcmus/mentor/backend/controller/payload/response/messages/MessageResponse.java
- src/src/main/java/com/hcmus/mentor/backend/service/SocketIOService.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/MessageServiceImpl.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/SocketIOServiceImpl.java
https://somesandwich2.atlassian.net/browse/MU-284
> Add field isForward to message response MU-284

- src/src/main/java/com/hcmus/mentor/backend/controller/payload/request/CreateVoteRequest.java
- src/src/main/java/com/hcmus/mentor/backend/controller/payload/response/votes/VoteDetailResponse.java
- src/src/main/java/com/hcmus/mentor/backend/domain/Vote.java
https://somesandwich2.atlassian.net/browse/MU-285
> Add field isMultipleChoice to Vote entity MU-285

- src/src/main/java/com/hcmus/mentor/backend/controller/GroupController.java
- src/src/main/java/com/hcmus/mentor/backend/domain/Channel.java
- src/src/main/java/com/hcmus/mentor/backend/domain/Group.java
- src/src/main/java/com/hcmus/mentor/backend/repository/ChannelRepository.java
- src/src/main/java/com/hcmus/mentor/backend/repository/GroupRepository.java
- src/src/main/java/com/hcmus/mentor/backend/repository/MessageRepository.java
- src/src/main/java/com/hcmus/mentor/backend/service/GroupService.java
- src/src/main/java/com/hcmus/mentor/backend/service/ShareService.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/AnalyticServiceImpl.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/GroupServiceImpl.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/ShareServiceImpl.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/UserServiceImpl.java
https://somesandwich2.atlassian.net/browse/MU-265
> Revise the api path for group details MU-265

- src/src/main/java/com/hcmus/mentor/backend/controller/ChannelController.java
- src/src/main/java/com/hcmus/mentor/backend/service/ChannelService.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/ChannelServiceImpl.java
https://somesandwich2.atlassian.net/browse/MU-263
> Update remove channel not allow default channel MU-263

- src/src/main/java/com/hcmus/mentor/backend/controller/payload/response/messages/MessageDetailResponse.java
- src/src/main/java/com/hcmus/mentor/backend/controller/payload/response/messages/MessageResponse.java
- src/src/main/java/com/hcmus/mentor/backend/domain/Message.java
- src/src/main/java/com/hcmus/mentor/backend/service/ShareService.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/MessageServiceImpl.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/NotificationServiceImpl.java
https://somesandwich2.atlassian.net/browse/MU-288
> Update api forward message to allow forward media type

- src/src/main/java/com/hcmus/mentor/backend/security/SecurityConfig.java
- src/src/main/java/com/hcmus/mentor/backend/security/filter/JwtAuthFilter.java
- src/src/main/java/com/hcmus/mentor/backend/security/handler/Http401UnauthorizedEntryPoint.java
https://somesandwich2.atlassian.net/browse/MU-289
> Add 401 entrypoint for validate request MU-289

- src/src/main/java/com/hcmus/mentor/backend/controller/GroupController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/TaskController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/VoteController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/payload/request/AddTaskRequest.java
- src/src/main/java/com/hcmus/mentor/backend/domain/Channel.java
- src/src/main/java/com/hcmus/mentor/backend/repository/ChannelRepository.java
- src/src/main/java/com/hcmus/mentor/backend/service/PermissionService.java
- src/src/main/java/com/hcmus/mentor/backend/service/TaskServiceImpl.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/GroupServiceImpl.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/PermissionServiceImpl.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/VoteServiceImpl.java
https://somesandwich2.atlassian.net/browse/MU-265
> Update for create task, meeting, vote for channelId MU-265

- src/src/main/java/com/hcmus/mentor/backend/controller/socketio/SocketController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/channel/updatelastmessage/UpdateLastMessageCommand.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/channel/updatelastmessage/UpdateLastMessageHandler.java
- src/src/main/java/com/hcmus/mentor/backend/service/GroupService.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/GroupServiceImpl.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/MessageServiceImpl.java
https://somesandwich2.atlassian.net/browse/MU-265
> Update last message in channel MU-265

- src/src/main/java/com/hcmus/mentor/backend/controller/ChannelController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/MeetingController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/TaskController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/VoteController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/channel/getmediabychannelid/GetMediaByChannelIdQuery.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/channel/getmediabychannelid/GetMediaByChannelIdQueryHandler.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/channel/getmeetingsbychannelid/GetMeetingsByChannelIdQuery.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/channel/getmeetingsbychannelid/GetMeetingsByChannelIdQueryHandler.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/channel/getmembersbychannelid/GetMembersByChannelIdQuery.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/channel/getmembersbychannelid/GetMembersByChannelIdQueryHandler.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/channel/gettasksbychannelid/GetTasksByIdQuery.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/channel/gettasksbychannelid/GetTasksByIdQueryHandler.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/channel/getvotesbychannelid/GetVotesByChannelIdQuery.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/channel/getvotesbychannelid/GetVotesByChannelIdQueryHandler.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/channel/updatelastmessage/UpdateLastMessageCommandHandler.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/meeting/common/MeetingResult.java
- src/src/main/java/com/hcmus/mentor/backend/repository/MeetingRepository.java
- src/src/main/java/com/hcmus/mentor/backend/repository/TaskRepository.java
- src/src/main/java/com/hcmus/mentor/backend/repository/VoteRepository.java
- src/src/main/java/com/hcmus/mentor/backend/service/MeetingService.java
- src/src/main/java/com/hcmus/mentor/backend/service/TaskServiceImpl.java
- src/src/main/java/com/hcmus/mentor/backend/service/VoteService.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/PermissionServiceImpl.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/VoteServiceImpl.java
https://somesandwich2.atlassian.net/browse/MU-265
> Feature/MU  265 update api vote meeting task for channel

- .github/dependabot.yml
- src/src/main/resources/application-dev.yml.template
- src/src/main/resources/application-prod.yml.template
> Push to main

- src/src/main/java/com/hcmus/mentor/backend/controller/UserController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/payload/response/users/ProfileResponse.java
https://somesandwich2.atlassian.net/browse/MU-294
> Add role for return user profile MU-305

- src/src/main/java/com/hcmus/mentor/backend/controller/GroupController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/group/GroupMapper.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/group/getgroupworkspace/GetGroupWorkSpaceQuery.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/group/getgroupworkspace/GetGroupWorkspaceQueryHandler.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/group/getgroupworkspace/GetGroupWorkspaceResult.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/group/getgroupworkspace/WorkspaceChannelDto.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/GroupServiceImpl.java
https://somesandwich2.atlassian.net/browse/MU-324
> Return information for file mentors mentees role in workspace API MU-324

- src/src/main/java/com/hcmus/mentor/backend/controller/ChannelController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/GroupController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/channel/ChannelMapper.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/channel/addchannel/AddChannelCommandHandler.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/channel/common/ChannelDetailDto.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/channel/getchannelbyid/GetChannelByIdQuery.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/channel/getchannelbyid/GetChannelByIdQueryHandler.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/group/GroupMapper.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/group/common/GroupHomepageDto.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/group/common/GroupWorkspaceDto.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/group/common/WorkspaceChannelDto.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/group/getgroupworkspace/GetGroupWorkSpaceQuery.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/group/getgroupworkspace/GetGroupWorkspaceQueryHandler.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/group/importgroup/ImportGroupCommand.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/group/searchowngroups/SearchOwnGroupsQuery.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/group/searchowngroups/SearchOwnGroupsQueryHandler.java
- src/src/main/java/com/hcmus/mentor/backend/repository/UserRepository.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/EventServiceImpl.java
- src/src/main/java/com/hcmus/mentor/backend/util/MapperUtil.java
https://somesandwich2.atlassian.net/browse/MU-333
> Improve the GetChannelDetail MU-333

- src/src/main/java/com/hcmus/mentor/backend/controller/GroupController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/group/updategroupbyid/UpdateGroupByIdCommandHandler.java
https://somesandwich2.atlassian.net/browse/MU-371
> Fix update group MU-371

- src/src/main/java/com/hcmus/mentor/backend/repository/GroupCategoryRepository.java
https://somesandwich2.atlassian.net/browse/MU-370
> Fix search group category MU-370

- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/course/common/CourseDto.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/schoolyear/common/SchoolYearDto.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/semester/common/SemesterDto.java
https://somesandwich2.atlassian.net/browse/MU-404
> Add id for dto of course, school year, semester MU-404

- src/src/main/java/com/hcmus/mentor/backend/controller/payload/request/note/CreateNoteRequest.java
- src/src/main/java/com/hcmus/mentor/backend/controller/payload/request/note/ShareNoteRequest.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/note/common/NoteDetailDto.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/note/common/NoteDto.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/note/createnote/CreateNoteCommand.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/note/createnote/CreateNoteCommandHandler.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/note/deletenote/DeleteNoteCommandHandler.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/note/getnotedetailbyid/GetNoteDetailByIdQueryHandler.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/note/searchuserhasnotebyviewer/SearchUserHasNoteByViewerQueryHandler.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/note/sharenote/ShareNoteCommand.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/note/sharenote/ShareNoteCommandHandler.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/user/searchmenteesofuser/SearchMenteeOfUserCommandHandler.java
- src/src/main/java/com/hcmus/mentor/backend/domain/Note.java
- src/src/main/java/com/hcmus/mentor/backend/domain/NoteHistory.java
- src/src/main/java/com/hcmus/mentor/backend/domain/constant/NoteShareType.java
- src/src/main/java/com/hcmus/mentor/backend/repository/UserRepository.java
- src/src/main/java/com/hcmus/mentor/backend/repository/custom/UserCustomRepository.java
- src/src/main/java/com/hcmus/mentor/backend/repository/custom/impl/UserRepositoryImpl.java
- src/src/main/resources/db/migration/V13__alter_table_notes__note_histories.sql
https://somesandwich2.atlassian.net/browse/MU-405
> Fix api search user has note and migrate note entity MU-405

- src/src/main/java/com/hcmus/mentor/backend/controller/CourseController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/GradeController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/SchoolYearController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/SemesterController.java
https://somesandwich2.atlassian.net/browse/MU-404
> Add docstring for course, semester, school year, grade MU-404

- src/src/main/java/com/hcmus/mentor/backend/repository/MessageRepository.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/MessageServiceImpl.java
https://somesandwich2.atlassian.net/browse/MU-378
> Filter meeting and task in message MU-378

- src/src/main/java/com/hcmus/mentor/backend/controller/GradeController.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/grade/sharegrade/ShareGradeCommand.java
- src/src/main/java/com/hcmus/mentor/backend/controller/usecase/grade/sharegrade/ShareGradeCommandHandler.java
- src/src/main/java/com/hcmus/mentor/backend/domain/GradeUserAccess.java
- src/src/main/java/com/hcmus/mentor/backend/domain/NoteUserAccess.java
- src/src/main/java/com/hcmus/mentor/backend/domain/User.java
- src/src/main/java/com/hcmus/mentor/backend/domain/constant/GradeShareType.java
- src/src/main/java/com/hcmus/mentor/backend/repository/GradeUserAccessRepository.java
- src/src/main/java/com/hcmus/mentor/backend/service/impl/UserServiceImpl.java
- src/src/main/resources/db/migration/V16__add_share_grade_domain.sql
- src/src/main/resources/db/migration/V17__add_column_grade_share_type__users.sql
https://somesandwich2.atlassian.net/browse/MU-367
> Feature/MU | 367 share grade
